In [1]:
import torch
torch.__version__

'1.13.1'

## Getting information from tensors

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype` 
2. to get shape from a tensor, can use `tenssor.shape`
3. to get device from a tensor, can use `tensor.device`

In [3]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.7270, 0.7193, 0.8589, 0.1749],
        [0.8376, 0.1742, 0.2271, 0.9332],
        [0.7124, 0.9096, 0.9646, 0.6465]])

In [4]:
print(some_tensor.dtype)
print(some_tensor.shape)
print(some_tensor.device)

torch.float32
torch.Size([3, 4])
cpu


### Manipulating Tensors (tensosr operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [6]:
# Create Tensors

tensor = torch.tensor([1,2,3])
print(tensor.dtype)
tensor + 10

torch.int64


tensor([11, 12, 13])

In [12]:
# Multiply tensor (element-wise)

tensor * 10

tensor([10, 20, 30])

In [9]:
# Subtract

tensor - 10

tensor([-9, -8, -7])

In [11]:
# try out Pytorch in-built functions

print(torch.mul(tensor,10))
print(torch.add(tensor,10))

tensor([10, 20, 30])
tensor([11, 12, 13])


### Matrix multiplication (dot product)

There are two rules
1. the **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(3,2) @ (2,3)` will work
2. The resulting matrix has the shape of the **outer dimension**:
* `(2,3) @ (3,2) = (2,2)`

In [14]:
# element-wise 
print(tensor)
print(tensor * tensor)

tensor([1, 2, 3])
tensor([1, 4, 9])


In [15]:
# dot product

print(torch.matmul(tensor,tensor))

tensor(14)


In [26]:
%%time
print(some_tensor.shape)
some_tensor1 = torch.rand(4,2)
print(some_tensor1.shape)

print(torch.matmul(some_tensor,some_tensor1))
print(torch.matmul(some_tensor,some_tensor1).shape)

torch.Size([3, 4])
torch.Size([4, 2])
tensor([[1.8878, 0.9233],
        [1.6709, 1.4053],
        [2.4847, 1.3423]])
torch.Size([3, 2])
CPU times: user 2.38 ms, sys: 1.67 ms, total: 4.05 ms
Wall time: 2.6 ms


In [22]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

CPU times: user 1.32 ms, sys: 1.54 ms, total: 2.86 ms
Wall time: 2.17 ms


tensor(14)

In [25]:
%%time

torch.matmul(tensor,tensor)

CPU times: user 37 µs, sys: 5 µs, total: 42 µs
Wall time: 47 µs


tensor(14)

In [27]:
torch.matmul(torch.rand(2,100),torch.rand(100,3))

tensor([[24.5067, 26.3759, 26.5329],
        [26.8635, 28.0669, 25.3205]])

### shape errors

In [30]:
# Shapes for matrix multiplications

tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                        [9,12]])
print(f'A shape : {tensor_A.shape}')
print(f'B shape : {tensor_B.shape}')
torch.mm(tensor_A,tensor_B)

A shape : torch.Size([3, 2])
B shape : torch.Size([3, 2])


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

### Manipulate the shape of tensors

A **transpose** switches the axes or dimensions

In [35]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [34]:
tensor_B.T,tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [33]:
torch.mm(tensor_A, tensor_B.T),torch.mm(tensor_A, tensor_B.T).shape 

(tensor([[ 27,  30,  33],
         [ 61,  68,  75],
         [ 95, 106, 117]]),
 torch.Size([3, 3]))

### Tensor aggregation
- min, max, mean, sum, etc

In [42]:
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [38]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [39]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [43]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [44]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [47]:
x.argmin(),torch.argmin(x)

(tensor(0), tensor(0))

In [48]:
x.argmax(), torch.argmax(x)

(tensor(9), tensor(9))

In [49]:
x[x.argmin()]

tensor(0)

In [50]:
x[x.argmax()]

tensor(90)

### Reshaping stacking squeezing unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensor on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [67]:
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [53]:
x_reshaped = x.reshape(1,7)

RuntimeError: shape '[1, 7]' is invalid for input of size 9

In [68]:
x_reshaped = x.reshape(1,9,1,1)
x_reshaped.shape

torch.Size([1, 9, 1, 1])

In [69]:
x_view = x.view(9,1)
x_view.shape

torch.Size([9, 1])

In [64]:
x_view[:,0] = 5
x_view, x, x_reshaped

(tensor([[5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.]]),
 tensor([5., 5., 5., 5., 5., 5., 5., 5., 5.]),
 tensor([[[[5.]],
 
          [[5.]],
 
          [[5.]],
 
          [[5.]],
 
          [[5.]],
 
          [[5.]],
 
          [[5.]],
 
          [[5.]],
 
          [[5.]]]]))

In [70]:
# Stack tensors on top of each other

x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [85]:
# Squeeze Unsqeeze

print(x.shape)
x_unsqueeze = x.unsqueeze(dim=1)
print(x_unsqueeze.shape)

torch.Size([9])
torch.Size([9, 1])


In [86]:
print(x_unsqueeze.shape)
x_squeeze  = x_unsqueeze.squeeze()
print(x_squeeze.shape)


torch.Size([9, 1])
torch.Size([9])


In [90]:
## torch.permute - rearrange the dimensions of a target tensor in a specifed order

x_original = torch.rand(size=(224,224,3))
print(x_original.shape)
x_permute = x_original.permute(2,0,1)
print(x_permute.shape)


torch.Size([224, 224, 3])
torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)

Indexing with Pytorch is similar to indexing with NumPy.

In [3]:
import torch

x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [8]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [10]:
x[0][0], x[0,0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [11]:
x[0][0][0], x[0,0,0]

(tensor(1), tensor(1))

In [12]:
x[:,0]

tensor([[1, 2, 3]])

In [13]:
# You can also use ":" to select "all" of a target dimension

x[:,:,1]

tensor([[2, 5, 8]])

In [15]:
x[:,1,:]

tensor([[4, 5, 6]])

## Pytorch tensors & Numpy

NumPy is a a popular scientific Python numerical computing library.

And because of this, Pytorch has functionlity to interact with it.

* Data in Numpy, want in Pytorch tensor -> `torch.from_numpy(ndarray)`
* Pytorch tensor -> Numpy -> `torch.Tensor.numpy()`

In [18]:
import torch
import numpy as np

array = np.arange(1.,8.)
tensor = torch.from_numpy(array)

array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [19]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float64)

In [20]:
torch.arange(1.,8.).dtype

torch.float32

In [21]:
array += array

array, tensor

(array([ 2.,  4.,  6.,  8., 10., 12., 14.]),
 tensor([ 2.,  4.,  6.,  8., 10., 12., 14.], dtype=torch.float64))

In [24]:
tensor = torch.ones(7)

numpy_tensor = tensor.numpy()

tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [25]:
tensor += 1

tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([2., 2., 2., 2., 2., 2., 2.], dtype=float32))

## trying to take random out of random

In short how a neural network learns:

`start with random numbers  -> tensors operations  -> update random numbers to try and make them of the data -> again -> again ...`

To reduce randomness in neural network and Pytorch comes the concept of a **random seedd**


Essentially what the random seedd does is "flavour" the randomness

In [47]:
import torch

random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.9811, 0.0874, 0.0041, 0.1088],
        [0.1637, 0.7025, 0.6790, 0.9155],
        [0.2418, 0.1591, 0.7653, 0.2979]])
tensor([[0.8035, 0.3813, 0.7860, 0.1115],
        [0.2477, 0.6524, 0.6057, 0.3725],
        [0.7980, 0.8399, 0.1374, 0.2331]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [82]:
import torch

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)
# torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [83]:
random_tensor_E = torch.rand(3,4)
print(random_tensor_E)

tensor([[0.1053, 0.2695, 0.3588, 0.1994],
        [0.5472, 0.0062, 0.9516, 0.0753],
        [0.8860, 0.5832, 0.3376, 0.8090]])


In [84]:
random_tensor_f = torch.rand(3,4)
print(random_tensor_f)

tensor([[0.5779, 0.9040, 0.5547, 0.3423],
        [0.6343, 0.3644, 0.7104, 0.9464],
        [0.7890, 0.2814, 0.7886, 0.5895]])


In [85]:
random_tensor_a = torch.rand(3,4)
print(random_tensor_a)

tensor([[0.7539, 0.1952, 0.0050, 0.3068],
        [0.1165, 0.9103, 0.6440, 0.7071],
        [0.6581, 0.4913, 0.8913, 0.1447]])


In [86]:
random_tensor_b = torch.rand(3,4)
print(random_tensor_b)

tensor([[0.5315, 0.1587, 0.6542, 0.3278],
        [0.6532, 0.3958, 0.9147, 0.2036],
        [0.2018, 0.2018, 0.9497, 0.6666]])


## GPUs


GPUs = faster computation on numbers

In [88]:
torch.cuda.is_available()

False

In [89]:
!nvidia-smi

/bin/bash: nvidia-smi: command not found


In [90]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'

In [91]:
torch.cuda.device_count()

0

## 